function rows = appendStructure(rows, measurements, subjectID, isKyphotic, group, structure)

    axes = {"X","Y","Z"};
    
    for lvl = 1:numel(measurements)
        meas = measurements(lvl);
    
        for a = 1:3
            ax = axes{a};

            numLevels = numel(meas.slicer);
    
            for k = 1:numLevels
                csa    = meas.slicer(k).csa.(ax);        % [Nslices × 1]
                widths = meas.slicer(k).widths.(ax);     % [Nslices × 2]
                slice  = meas.slicer(k).slice.(ax);      % [1 × Nslices]

                rows(end+1,:) = { ...
                    subjectID, ...
                    isKyphotic, ...
                    group, ...
                    categorical(structure), ...
                    lvl, ...
                    categorical(ax), ...
                    k, ...
                    slice(k), ...
                    csa(k), ...
                    widths(k,1), ...
                    widths(k,2) ...
                    };
            end
        end
    end
end

